### ISSUE TITLE
chore: request to move repository to chakra-ui organization

### ISSUE THREAD

**Issue by codebender828** [DominusKelvin/vue-cli-plugin-chakra-ui-vue#1]
Hey @DominusKelvin !

Thank you very much for the work done regarding the Chakra UI Vue CLI plugin.

After working on chakra-ui/chakra-ui-vue#307, I realised that it may be difficult to implement and maintain changes to the CLI plugin nuxt modules, and core ecosystem related packages(like `vue-cli-plugin-chakra-ui`) if they aren't located in the same organization. This would allow me to make changes faster.

For this reason, I think it's best to have the Vue CLI plugin repository moved to the [Chakra UI organization](https://github.com/chakra-ui) on Github.

**Comment by DominusKelvin** [comment]
Alright @codebender828. What needs to be done as regarding clean-ups?
